USE atc;

INSERT INTO credito (total, estado, orden_id) VALUES (11197, true, 1);
INSERT INTO credito (total, estado, orden_id) VALUES (15770, true, 2);
INSERT INTO credito (total, estado, orden_id) VALUES (13351, true, 3);
INSERT INTO credito (total, estado, orden_id) VALUES (13567, true, 4);
INSERT INTO credito (total, estado, orden_id) VALUES (2600, true, 5);
INSERT INTO credito (total, estado, orden_id) VALUES (13322, true, 6);
INSERT INTO credito (total, estado, orden_id) VALUES (26882, true, 7);
INSERT INTO credito (total, estado, orden_id) VALUES (26163, true, 8);
INSERT INTO credito (total, estado, orden_id) VALUES (15999, true, 9);
INSERT INTO credito (total, estado, orden_id) VALUES (6513, true, 10);
INSERT INTO credito (total, estado, orden_id) VALUES (8905, true, 11);
INSERT INTO credito (total, estado, orden_id) VALUES (10021, true, 12);
INSERT INTO credito (total, estado, orden_id) VALUES (11288, true, 13);
INSERT INTO credito (total, estado, orden_id) VALUES (19865, true, 14);
INSERT INTO credito (total, estado, orden_id) VALUES (25781, true, 15);
INSERT INTO credito (total, estado, orden_id) VALUES (18039, true, 16);
INSERT INTO credito (total, estado, orden_id) VALUES (7710, true, 17);
INSERT INTO credito (total, estado, orden_id) VALUES (2519, true, 18);
INSERT INTO credito (total, estado, orden_id) VALUES (29267, true, 19);
INSERT INTO credito (total, estado, orden_id) VALUES (27349, true, 20);
INSERT INTO credito (total, estado, orden_id) VALUES (3227, true, 21);
INSERT INTO credito (total, estado, orden_id) VALUES (25045, true, 22);
INSERT INTO credito (total, estado, orden_id) VALUES (23861, true, 23);
INSERT INTO credito (total, estado, orden_id) VALUES (14809, true, 24);
INSERT INTO credito (total, estado, orden_id) VALUES (14293, true, 25);
INSERT INTO credito (total, estado, orden_id) VALUES (16789, true, 26);
INSERT INTO credito (total, estado, orden_id) VALUES (6887, true, 27);
INSERT INTO credito (total, estado, orden_id) VALUES (26156, true, 28);
INSERT INTO credito (total, estado, orden_id) VALUES (3550, true, 29);
INSERT INTO credito (total, estado, orden_id) VALUES (3251, true, 30);
INSERT INTO credito (total, estado, orden_id) VALUES (14116, true, 31);
INSERT INTO credito (total, estado, orden_id) VALUES (26863, true, 32);
INSERT INTO credito (total, estado, orden_id) VALUES (3687, true, 33);
INSERT INTO credito (total, estado, orden_id) VALUES (17131, true, 34);
INSERT INTO credito (total, estado, orden_id) VALUES (30282, true, 35);
INSERT INTO credito (total, estado, orden_id) VALUES (27225, true, 36);
INSERT INTO credito (total, estado, orden_id) VALUES (8405, true, 37);
INSERT INTO credito (total, estado, orden_id) VALUES (19930, true, 38);
INSERT INTO credito (total, estado, orden_id) VALUES (31756, true, 39);
INSERT INTO credito (total, estado, orden_id) VALUES (7585, true, 40);
INSERT INTO credito (total, estado, orden_id) VALUES (4247, true, 41);
INSERT INTO credito (total, estado, orden_id) VALUES (23561, true, 42);
INSERT INTO credito (total, estado, orden_id) VALUES (19047, true, 43);
INSERT INTO credito (total, estado, orden_id) VALUES (5150, true, 44);
INSERT INTO credito (total, estado, orden_id) VALUES (9142, true, 45);
INSERT INTO credito (total, estado, orden_id) VALUES (27943, true, 46);
INSERT INTO credito (total, estado, orden_id) VALUES (11479, true, 47);
INSERT INTO credito (total, estado, orden_id) VALUES (19373, true, 48);
INSERT INTO credito (total, estado, orden_id) VALUES (32685, true, 49);
INSERT INTO credito (total, estado, orden_id) VALUES (29590, true, 50);
INSERT INTO credito (total, estado, orden_id) VALUES (25546, true, 51);
INSERT INTO credito (total, estado, orden_id) VALUES (31827, true, 52);
INSERT INTO credito (total, estado, orden_id) VALUES (20604, true, 53);
INSERT INTO credito (total, estado, orden_id) VALUES (12074, true, 54);
INSERT INTO credito (total, estado, orden_id) VALUES (9301, true, 55);
INSERT INTO credito (total, estado, orden_id) VALUES (26915, true, 56);
INSERT INTO credito (total, estado, orden_id) VALUES (26104, true, 57);
INSERT INTO credito (total, estado, orden_id) VALUES (9517, true, 58);
INSERT INTO credito (total, estado, orden_id) VALUES (16422, true, 59);
INSERT INTO credito (total, estado, orden_id) VALUES (14434, true, 60);
INSERT INTO credito (total, estado, orden_id) VALUES (15205, true, 61);
INSERT INTO credito (total, estado, orden_id) VALUES (22950, true, 62);
INSERT INTO credito (total, estado, orden_id) VALUES (2490, true, 63);
INSERT INTO credito (total, estado, orden_id) VALUES (5866, true, 64);
INSERT INTO credito (total, estado, orden_id) VALUES (7494, true, 65);
INSERT INTO credito (total, estado, orden_id) VALUES (11738, true, 66);
INSERT INTO credito (total, estado, orden_id) VALUES (18640, true, 67);
INSERT INTO credito (total, estado, orden_id) VALUES (10956, true, 68);
INSERT INTO credito (total, estado, orden_id) VALUES (24948, true, 69);
INSERT INTO credito (total, estado, orden_id) VALUES (2068, true, 70);
INSERT INTO credito (total, estado, orden_id) VALUES (21277, true, 71);
INSERT INTO credito (total, estado, orden_id) VALUES (6457, true, 72);
INSERT INTO credito (total, estado, orden_id) VALUES (25966, true, 73);
INSERT INTO credito (total, estado, orden_id) VALUES (10402, true, 74);
INSERT INTO credito (total, estado, orden_id) VALUES (7489, true, 75);
INSERT INTO credito (total, estado, orden_id) VALUES (9123, true, 76);
INSERT INTO credito (total, estado, orden_id) VALUES (18160, true, 77);
INSERT INTO credito (total, estado, orden_id) VALUES (20512, true, 78);
INSERT INTO credito (total, estado, orden_id) VALUES (22522, true, 79);
INSERT INTO credito (total, estado, orden_id) VALUES (8223, true, 80);
INSERT INTO credito (total, estado, orden_id) VALUES (2759, true, 81);
INSERT INTO credito (total, estado, orden_id) VALUES (6905, true, 82);
INSERT INTO credito (total, estado, orden_id) VALUES (28055, true, 83);
INSERT INTO credito (total, estado, orden_id) VALUES (20750, true, 84);
INSERT INTO credito (total, estado, orden_id) VALUES (9699, true, 85);
INSERT INTO credito (total, estado, orden_id) VALUES (13866, true, 86);
INSERT INTO credito (total, estado, orden_id) VALUES (29616, true, 87);
INSERT INTO credito (total, estado, orden_id) VALUES (24572, true, 88);
INSERT INTO credito (total, estado, orden_id) VALUES (7342, true, 89);
INSERT INTO credito (total, estado, orden_id) VALUES (20809, true, 90);
INSERT INTO credito (total, estado, orden_id) VALUES (25877, true, 91);
INSERT INTO credito (total, estado, orden_id) VALUES (32712, true, 92);
INSERT INTO credito (total, estado, orden_id) VALUES (11420, true, 93);
INSERT INTO credito (total, estado, orden_id) VALUES (29126, true, 94);
INSERT INTO credito (total, estado, orden_id) VALUES (14340, true, 95);
INSERT INTO credito (total, estado, orden_id) VALUES (31237, true, 96);
INSERT INTO credito (total, estado, orden_id) VALUES (13315, true, 97);
INSERT INTO credito (total, estado, orden_id) VALUES (2930, true, 98);
INSERT INTO credito (total, estado, orden_id) VALUES (9375, true, 99);
INSERT INTO credito (total, estado, orden_id) VALUES (11169, true, 100);
INSERT INTO credito (total, estado, orden_id) VALUES (19502, true, 101);
INSERT INTO credito (total, estado, orden_id) VALUES (573, true, 102);
INSERT INTO credito (total, estado, orden_id) VALUES (12188, true, 103);
INSERT INTO credito (total, estado, orden_id) VALUES (13508, true, 104);
INSERT INTO credito (total, estado, orden_id) VALUES (18861, true, 105);
INSERT INTO credito (total, estado, orden_id) VALUES (31044, true, 106);
INSERT INTO credito (total, estado, orden_id) VALUES (19775, true, 107);
INSERT INTO credito (total, estado, orden_id) VALUES (24571, true, 108);
INSERT INTO credito (total, estado, orden_id) VALUES (5870, true, 109);
INSERT INTO credito (total, estado, orden_id) VALUES (4875, true, 110);
INSERT INTO credito (total, estado, orden_id) VALUES (12421, true, 111);
INSERT INTO credito (total, estado, orden_id) VALUES (1174, true, 112);
INSERT INTO credito (total, estado, orden_id) VALUES (7442, true, 113);
INSERT INTO credito (total, estado, orden_id) VALUES (1798, true, 114);
INSERT INTO credito (total, estado, orden_id) VALUES (6819, true, 115);
INSERT INTO credito (total, estado, orden_id) VALUES (26703, true, 116);
INSERT INTO credito (total, estado, orden_id) VALUES (12025, true, 117);
INSERT INTO credito (total, estado, orden_id) VALUES (12383, true, 118);
INSERT INTO credito (total, estado, orden_id) VALUES (16046, true, 119);
INSERT INTO credito (total, estado, orden_id) VALUES (25644, true, 120);
INSERT INTO credito (total, estado, orden_id) VALUES (10911, true, 121);
INSERT INTO credito (total, estado, orden_id) VALUES (31219, true, 122);
INSERT INTO credito (total, estado, orden_id) VALUES (3484, true, 123);
INSERT INTO credito (total, estado, orden_id) VALUES (20646, true, 124);
INSERT INTO credito (total, estado, orden_id) VALUES (17580, true, 125);
INSERT INTO credito (total, estado, orden_id) VALUES (19358, true, 126);
INSERT INTO credito (total, estado, orden_id) VALUES (32363, true, 127);
INSERT INTO credito (total, estado, orden_id) VALUES (32010, true, 128);
INSERT INTO credito (total, estado, orden_id) VALUES (12870, true, 129);
INSERT INTO credito (total, estado, orden_id) VALUES (23736, true, 130);
INSERT INTO credito (total, estado, orden_id) VALUES (9888, true, 131);
INSERT INTO credito (total, estado, orden_id) VALUES (13856, true, 132);
INSERT INTO credito (total, estado, orden_id) VALUES (9514, true, 133);
INSERT INTO credito (total, estado, orden_id) VALUES (4063, true, 134);
INSERT INTO credito (total, estado, orden_id) VALUES (14067, true, 135);
INSERT INTO credito (total, estado, orden_id) VALUES (8203, true, 136);
INSERT INTO credito (total, estado, orden_id) VALUES (19963, true, 137);
INSERT INTO credito (total, estado, orden_id) VALUES (15351, true, 138);
INSERT INTO credito (total, estado, orden_id) VALUES (12361, true, 139);
INSERT INTO credito (total, estado, orden_id) VALUES (26480, true, 140);
INSERT INTO credito (total, estado, orden_id) VALUES (22745, true, 141);
INSERT INTO credito (total, estado, orden_id) VALUES (1648, true, 142);
INSERT INTO credito (total, estado, orden_id) VALUES (25826, true, 143);
INSERT INTO credito (total, estado, orden_id) VALUES (3546, true, 144);
INSERT INTO credito (total, estado, orden_id) VALUES (6198, true, 145);
INSERT INTO credito (total, estado, orden_id) VALUES (12999, true, 146);
INSERT INTO credito (total, estado, orden_id) VALUES (6612, true, 147);
INSERT INTO credito (total, estado, orden_id) VALUES (21853, true, 148);
INSERT INTO credito (total, estado, orden_id) VALUES (20965, true, 149);
INSERT INTO credito (total, estado, orden_id) VALUES (2896, true, 150);
INSERT INTO credito (total, estado, orden_id) VALUES (23736, true, 151);
INSERT INTO credito (total, estado, orden_id) VALUES (3962, true, 152);
INSERT INTO credito (total, estado, orden_id) VALUES (25204, true, 153);
INSERT INTO credito (total, estado, orden_id) VALUES (18226, true, 154);
INSERT INTO credito (total, estado, orden_id) VALUES (24995, true, 155);
INSERT INTO credito (total, estado, orden_id) VALUES (21315, true, 156);
INSERT INTO credito (total, estado, orden_id) VALUES (10940, true, 157);
INSERT INTO credito (total, estado, orden_id) VALUES (4531, true, 158);
INSERT INTO credito (total, estado, orden_id) VALUES (32088, true, 159);
INSERT INTO credito (total, estado, orden_id) VALUES (24255, true, 160);
INSERT INTO credito (total, estado, orden_id) VALUES (31670, true, 161);
INSERT INTO credito (total, estado, orden_id) VALUES (5814, true, 162);
INSERT INTO credito (total, estado, orden_id) VALUES (4027, true, 163);
INSERT INTO credito (total, estado, orden_id) VALUES (10128, true, 164);
INSERT INTO credito (total, estado, orden_id) VALUES (29841, true, 165);
INSERT INTO credito (total, estado, orden_id) VALUES (14465, true, 166);
INSERT INTO credito (total, estado, orden_id) VALUES (29321, true, 167);
INSERT INTO credito (total, estado, orden_id) VALUES (24275, true, 168);
INSERT INTO credito (total, estado, orden_id) VALUES (1793, true, 169);
INSERT INTO credito (total, estado, orden_id) VALUES (21188, true, 170);
INSERT INTO credito (total, estado, orden_id) VALUES (16455, true, 171);
INSERT INTO credito (total, estado, orden_id) VALUES (27720, true, 172);
INSERT INTO credito (total, estado, orden_id) VALUES (5593, true, 173);
INSERT INTO credito (total, estado, orden_id) VALUES (11991, true, 174);
INSERT INTO credito (total, estado, orden_id) VALUES (1912, true, 175);
INSERT INTO credito (total, estado, orden_id) VALUES (9395, true, 176);
INSERT INTO credito (total, estado, orden_id) VALUES (25052, true, 177);
INSERT INTO credito (total, estado, orden_id) VALUES (3396, true, 178);
INSERT INTO credito (total, estado, orden_id) VALUES (15891, true, 179);
INSERT INTO credito (total, estado, orden_id) VALUES (16258, true, 180);
INSERT INTO credito (total, estado, orden_id) VALUES (14544, true, 181);
INSERT INTO credito (total, estado, orden_id) VALUES (26757, true, 182);
INSERT INTO credito (total, estado, orden_id) VALUES (2356, true, 183);
INSERT INTO credito (total, estado, orden_id) VALUES (20399, true, 184);
INSERT INTO credito (total, estado, orden_id) VALUES (6869, true, 185);
INSERT INTO credito (total, estado, orden_id) VALUES (21775, true, 186);
INSERT INTO credito (total, estado, orden_id) VALUES (11538, true, 187);
INSERT INTO credito (total, estado, orden_id) VALUES (17384, true, 188);
INSERT INTO credito (total, estado, orden_id) VALUES (18933, true, 189);
INSERT INTO credito (total, estado, orden_id) VALUES (8847, true, 190);
INSERT INTO credito (total, estado, orden_id) VALUES (14641, true, 191);
INSERT INTO credito (total, estado, orden_id) VALUES (12782, true, 192);
INSERT INTO credito (total, estado, orden_id) VALUES (30716, true, 193);
INSERT INTO credito (total, estado, orden_id) VALUES (8819, true, 194);
INSERT INTO credito (total, estado, orden_id) VALUES (17625, true, 195);
INSERT INTO credito (total, estado, orden_id) VALUES (28987, true, 196);
INSERT INTO credito (total, estado, orden_id) VALUES (1674, true, 197);
INSERT INTO credito (total, estado, orden_id) VALUES (14252, true, 198);
INSERT INTO credito (total, estado, orden_id) VALUES (20422, true, 199);
INSERT INTO credito (total, estado, orden_id) VALUES (18663, true, 200);
INSERT INTO credito (total, estado, orden_id) VALUES (3430, true, 201);
INSERT INTO credito (total, estado, orden_id) VALUES (5042, true, 202);
INSERT INTO credito (total, estado, orden_id) VALUES (6945, true, 203);
INSERT INTO credito (total, estado, orden_id) VALUES (13516, true, 204);
INSERT INTO credito (total, estado, orden_id) VALUES (6933, true, 205);
INSERT INTO credito (total, estado, orden_id) VALUES (17609, true, 206);
INSERT INTO credito (total, estado, orden_id) VALUES (3759, true, 207);
INSERT INTO credito (total, estado, orden_id) VALUES (1513, true, 208);
INSERT INTO credito (total, estado, orden_id) VALUES (25516, true, 209);
INSERT INTO credito (total, estado, orden_id) VALUES (31108, true, 210);
INSERT INTO credito (total, estado, orden_id) VALUES (32329, true, 211);
INSERT INTO credito (total, estado, orden_id) VALUES (25092, true, 212);
INSERT INTO credito (total, estado, orden_id) VALUES (20962, true, 213);
INSERT INTO credito (total, estado, orden_id) VALUES (7559, true, 214);
INSERT INTO credito (total, estado, orden_id) VALUES (25484, true, 215);
INSERT INTO credito (total, estado, orden_id) VALUES (26259, true, 216);
INSERT INTO credito (total, estado, orden_id) VALUES (11881, true, 217);
INSERT INTO credito (total, estado, orden_id) VALUES (13200, true, 218);
INSERT INTO credito (total, estado, orden_id) VALUES (24529, true, 219);
INSERT INTO credito (total, estado, orden_id) VALUES (29405, true, 220);
INSERT INTO credito (total, estado, orden_id) VALUES (20863, true, 221);
INSERT INTO credito (total, estado, orden_id) VALUES (4281, true, 222);
INSERT INTO credito (total, estado, orden_id) VALUES (6751, true, 223);
INSERT INTO credito (total, estado, orden_id) VALUES (23901, true, 224);
INSERT INTO credito (total, estado, orden_id) VALUES (4800, true, 225);
INSERT INTO credito (total, estado, orden_id) VALUES (23799, true, 226);
INSERT INTO credito (total, estado, orden_id) VALUES (20192, true, 227);
INSERT INTO credito (total, estado, orden_id) VALUES (6247, true, 228);
INSERT INTO credito (total, estado, orden_id) VALUES (27454, true, 229);
INSERT INTO credito (total, estado, orden_id) VALUES (31975, true, 230);
INSERT INTO credito (total, estado, orden_id) VALUES (8210, true, 231);
INSERT INTO credito (total, estado, orden_id) VALUES (2574, true, 232);
INSERT INTO credito (total, estado, orden_id) VALUES (32211, true, 233);
INSERT INTO credito (total, estado, orden_id) VALUES (18634, true, 234);
INSERT INTO credito (total, estado, orden_id) VALUES (703, true, 235);
INSERT INTO credito (total, estado, orden_id) VALUES (6980, true, 236);
INSERT INTO credito (total, estado, orden_id) VALUES (31158, true, 237);
INSERT INTO credito (total, estado, orden_id) VALUES (13517, true, 238);
INSERT INTO credito (total, estado, orden_id) VALUES (21743, true, 239);
INSERT INTO credito (total, estado, orden_id) VALUES (16963, true, 240);
INSERT INTO credito (total, estado, orden_id) VALUES (2893, true, 241);
INSERT INTO credito (total, estado, orden_id) VALUES (20111, true, 242);
INSERT INTO credito (total, estado, orden_id) VALUES (30044, true, 243);
INSERT INTO credito (total, estado, orden_id) VALUES (3116, true, 244);
INSERT INTO credito (total, estado, orden_id) VALUES (20290, true, 245);
INSERT INTO credito (total, estado, orden_id) VALUES (13277, true, 246);
INSERT INTO credito (total, estado, orden_id) VALUES (28454, true, 247);
INSERT INTO credito (total, estado, orden_id) VALUES (27118, true, 248);
INSERT INTO credito (total, estado, orden_id) VALUES (31705, true, 249);
INSERT INTO credito (total, estado, orden_id) VALUES (26304, true, 250);
INSERT INTO credito (total, estado, orden_id) VALUES (3528, true, 251);
INSERT INTO credito (total, estado, orden_id) VALUES (17514, true, 252);
INSERT INTO credito (total, estado, orden_id) VALUES (13441, true, 253);
INSERT INTO credito (total, estado, orden_id) VALUES (8889, true, 254);
INSERT INTO credito (total, estado, orden_id) VALUES (27979, true, 255);
INSERT INTO credito (total, estado, orden_id) VALUES (7125, true, 256);
INSERT INTO credito (total, estado, orden_id) VALUES (15273, true, 257);
INSERT INTO credito (total, estado, orden_id) VALUES (5963, true, 258);
INSERT INTO credito (total, estado, orden_id) VALUES (23226, true, 259);
INSERT INTO credito (total, estado, orden_id) VALUES (13917, true, 260);
INSERT INTO credito (total, estado, orden_id) VALUES (30420, true, 261);
INSERT INTO credito (total, estado, orden_id) VALUES (11194, true, 262);
INSERT INTO credito (total, estado, orden_id) VALUES (6357, true, 263);
INSERT INTO credito (total, estado, orden_id) VALUES (8719, true, 264);
INSERT INTO credito (total, estado, orden_id) VALUES (30960, true, 265);
INSERT INTO credito (total, estado, orden_id) VALUES (12307, true, 266);
INSERT INTO credito (total, estado, orden_id) VALUES (23817, true, 267);
INSERT INTO credito (total, estado, orden_id) VALUES (3576, true, 268);
INSERT INTO credito (total, estado, orden_id) VALUES (1763, true, 269);
INSERT INTO credito (total, estado, orden_id) VALUES (8044, true, 270);
INSERT INTO credito (total, estado, orden_id) VALUES (6304, true, 271);
INSERT INTO credito (total, estado, orden_id) VALUES (16010, true, 272);
INSERT INTO credito (total, estado, orden_id) VALUES (19048, true, 273);
INSERT INTO credito (total, estado, orden_id) VALUES (22381, true, 274);
INSERT INTO credito (total, estado, orden_id) VALUES (25142, true, 275);
INSERT INTO credito (total, estado, orden_id) VALUES (8514, true, 276);
INSERT INTO credito (total, estado, orden_id) VALUES (10009, true, 277);
INSERT INTO credito (total, estado, orden_id) VALUES (26895, true, 278);
INSERT INTO credito (total, estado, orden_id) VALUES (4972, true, 279);
INSERT INTO credito (total, estado, orden_id) VALUES (17288, true, 280);
INSERT INTO credito (total, estado, orden_id) VALUES (26060, true, 281);
INSERT INTO credito (total, estado, orden_id) VALUES (26276, true, 282);
INSERT INTO credito (total, estado, orden_id) VALUES (28384, true, 283);
INSERT INTO credito (total, estado, orden_id) VALUES (12503, true, 284);
INSERT INTO credito (total, estado, orden_id) VALUES (10787, true, 285);
INSERT INTO credito (total, estado, orden_id) VALUES (21272, true, 286);
INSERT INTO credito (total, estado, orden_id) VALUES (25180, true, 287);
INSERT INTO credito (total, estado, orden_id) VALUES (31773, true, 288);
INSERT INTO credito (total, estado, orden_id) VALUES (26207, true, 289);
INSERT INTO credito (total, estado, orden_id) VALUES (5750, true, 290);
INSERT INTO credito (total, estado, orden_id) VALUES (14669, true, 291);
INSERT INTO credito (total, estado, orden_id) VALUES (30821, true, 292);
INSERT INTO credito (total, estado, orden_id) VALUES (16757, true, 293);
INSERT INTO credito (total, estado, orden_id) VALUES (7085, true, 294);
INSERT INTO credito (total, estado, orden_id) VALUES (21367, true, 295);
INSERT INTO credito (total, estado, orden_id) VALUES (25779, true, 296);
INSERT INTO credito (total, estado, orden_id) VALUES (9060, true, 297);
INSERT INTO credito (total, estado, orden_id) VALUES (31637, true, 298);
INSERT INTO credito (total, estado, orden_id) VALUES (13288, true, 299);

INSERT INTO bono_credito (cantidad, credito_id) VALUES (662, 64);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (333, 170);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (852, 45);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (625, 216);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (916, 44);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (817, 285);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (980, 168);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (474, 4);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (976, 52);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (580, 107);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (686, 184);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (344, 60);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (785, 11);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (336, 44);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (19, 125);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (623, 267);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (145, 55);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (297, 148);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (866, 268);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (659, 208);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (64, 182);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (150, 89);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (530, 201);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (760, 73);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (649, 200);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (372, 217);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (409, 94);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (195, 35);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (946, 243);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (699, 245);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (1000, 115);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (687, 95);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (800, 209);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (935, 106);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (533, 128);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (609, 207);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (809, 34);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (472, 272);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (167, 106);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (900, 214);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (145, 252);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (362, 23);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (517, 14);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (222, 168);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (238, 193);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (494, 125);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (576, 284);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (761, 187);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (251, 45);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (159, 62);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (732, 254);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (882, 9);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (728, 133);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (190, 247);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (515, 270);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (821, 231);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (649, 77);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (271, 226);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (338, 252);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (296, 91);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (411, 127);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (481, 195);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (738, 82);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (155, 203);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (546, 81);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (730, 131);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (777, 129);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (351, 20);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (750, 147);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (416, 220);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (934, 238);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (684, 8);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (1000, 82);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (897, 290);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (704, 203);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (521, 224);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (106, 150);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (733, 101);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (216, 46);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (808, 183);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (13, 13);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (951, 93);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (250, 262);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (351, 101);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (992, 186);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (415, 36);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (288, 278);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (272, 177);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (624, 220);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (51, 79);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (183, 219);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (393, 99);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (546, 12);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (865, 50);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (472, 11);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (421, 55);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (707, 214);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (902, 127);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (704, 152);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (74, 192);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (89, 169);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (690, 171);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (640, 181);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (601, 154);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (831, 246);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (618, 90);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (78, 82);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (641, 65);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (149, 233);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (573, 118);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (242, 95);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (788, 223);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (197, 192);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (511, 79);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (963, 188);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (176, 150);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (864, 154);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (826, 166);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (631, 0);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (79, 103);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (823, 225);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (32, 113);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (734, 157);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (848, 84);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (609, 140);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (561, 209);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (464, 10);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (164, 243);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (244, 266);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (483, 260);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (586, 186);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (778, 113);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (492, 238);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (717, 259);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (798, 6);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (579, 240);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (846, 161);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (268, 14);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (159, 203);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (598, 105);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (280, 38);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (382, 299);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (113, 125);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (38, 255);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (421, 261);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (601, 278);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (335, 113);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (855, 2);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (734, 196);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (269, 56);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (482, 132);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (596, 125);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (572, 201);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (918, 247);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (401, 138);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (100, 225);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (400, 103);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (131, 56);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (132, 168);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (984, 43);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (731, 76);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (426, 277);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (776, 266);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (151, 22);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (6, 72);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (2, 295);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (998, 65);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (627, 270);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (795, 161);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (47, 74);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (244, 266);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (25, 18);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (26, 218);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (449, 120);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (434, 222);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (580, 112);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (221, 84);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (597, 297);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (678, 164);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (267, 224);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (76, 124);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (210, 278);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (161, 150);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (558, 136);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (889, 139);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (565, 217);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (975, 20);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (973, 14);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (405, 139);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (287, 59);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (971, 59);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (794, 212);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (362, 65);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (530, 247);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (313, 216);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (498, 275);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (831, 178);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (503, 276);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (754, 159);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (439, 65);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (120, 264);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (931, 98);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (84, 156);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (705, 220);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (67, 68);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (141, 209);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (895, 13);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (288, 244);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (979, 174);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (489, 161);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (689, 121);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (604, 61);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (281, 2);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (264, 21);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (834, 83);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (782, 115);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (102, 283);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (910, 108);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (865, 149);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (676, 28);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (962, 142);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (819, 203);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (629, 6);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (656, 93);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (480, 139);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (979, 80);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (317, 4);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (738, 213);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (16, 205);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (726, 148);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (657, 174);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (257, 228);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (340, 205);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (584, 99);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (47, 36);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (270, 245);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (395, 239);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (210, 139);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (335, 250);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (418, 254);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (697, 230);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (119, 9);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (678, 181);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (514, 11);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (821, 39);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (664, 155);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (287, 74);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (234, 226);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (457, 25);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (576, 91);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (861, 112);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (800, 261);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (790, 283);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (209, 218);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (907, 182);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (20, 74);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (278, 120);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (573, 146);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (524, 55);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (175, 54);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (527, 59);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (862, 141);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (219, 280);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (9, 280);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (663, 69);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (55, 136);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (813, 226);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (736, 279);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (923, 166);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (560, 5);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (210, 261);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (608, 19);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (526, 164);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (782, 29);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (343, 55);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (958, 56);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (856, 297);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (488, 170);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (455, 83);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (36, 245);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (820, 209);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (500, 18);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (373, 254);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (17, 255);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (225, 223);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (16, 227);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (916, 9);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (949, 100);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (330, 147);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (497, 124);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (591, 36);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (729, 176);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (647, 59);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (951, 270);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (33, 228);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (237, 291);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (609, 191);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (703, 153);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (750, 127);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (504, 157);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (945, 294);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (176, 47);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (360, 131);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (580, 176);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (234, 72);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (550, 265);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (996, 7);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (815, 26);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (91, 290);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (738, 270);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (658, 254);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (155, 37);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (902, 228);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (768, 225);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (424, 65);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (455, 5);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (988, 132);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (184, 27);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (688, 261);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (892, 93);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (598, 109);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (550, 15);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (253, 3);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (937, 199);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (805, 109);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (882, 96);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (842, 255);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (567, 83);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (851, 219);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (344, 46);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (843, 85);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (821, 131);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (607, 125);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (961, 226);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (242, 155);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (973, 74);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (438, 70);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (184, 5);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (331, 49);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (45, 69);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (685, 110);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (262, 9);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (65, 15);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (176, 113);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (567, 25);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (854, 265);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (959, 55);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (18, 88);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (413, 204);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (274, 203);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (639, 60);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (376, 95);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (121, 76);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (684, 165);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (166, 128);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (485, 61);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (818, 161);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (230, 233);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (542, 112);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (310, 191);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (444, 257);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (338, 292);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (691, 170);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (855, 270);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (437, 106);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (667, 16);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (695, 49);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (43, 280);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (904, 255);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (59, 290);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (430, 145);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (297, 215);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (878, 71);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (522, 261);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (226, 43);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (65, 201);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (296, 193);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (845, 240);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (232, 15);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (835, 62);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (990, 78);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (996, 188);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (266, 250);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (617, 166);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (396, 6);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (931, 208);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (299, 264);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (679, 120);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (887, 120);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (883, 79);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (573, 34);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (626, 271);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (292, 89);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (502, 186);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (742, 265);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (855, 225);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (577, 105);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (430, 143);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (407, 246);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (663, 75);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (554, 6);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (167, 11);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (452, 172);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (529, 246);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (526, 199);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (136, 145);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (543, 65);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (176, 281);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (720, 74);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (213, 72);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (421, 221);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (809, 205);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (286, 247);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (680, 169);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (215, 181);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (679, 44);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (461, 270);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (476, 191);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (307, 282);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (671, 15);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (59, 73);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (649, 278);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (832, 8);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (524, 192);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (451, 284);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (195, 272);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (133, 139);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (219, 64);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (325, 203);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (3, 218);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (218, 25);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (88, 93);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (852, 155);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (116, 140);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (14, 229);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (855, 193);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (638, 209);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (335, 233);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (872, 226);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (476, 14);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (783, 194);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (511, 29);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (549, 98);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (68, 145);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (22, 49);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (501, 111);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (520, 31);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (10, 91);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (46, 157);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (886, 114);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (693, 238);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (531, 102);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (766, 20);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (184, 128);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (62, 103);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (930, 208);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (826, 257);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (233, 78);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (311, 71);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (733, 39);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (824, 266);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (289, 298);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (353, 118);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (958, 284);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (484, 247);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (898, 170);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (506, 193);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (771, 205);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (837, 125);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (735, 14);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (843, 252);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (550, 47);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (117, 264);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (978, 261);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (793, 153);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (285, 224);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (533, 210);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (556, 64);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (61, 255);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (139, 210);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (958, 105);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (577, 26);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (580, 101);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (413, 186);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (825, 117);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (297, 275);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (855, 5);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (622, 189);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (240, 112);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (977, 149);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (876, 265);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (492, 287);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (603, 144);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (272, 226);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (651, 241);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (993, 15);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (916, 49);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (658, 171);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (546, 94);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (387, 108);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (363, 196);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (264, 126);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (778, 153);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (900, 108);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (435, 208);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (702, 42);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (175, 246);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (51, 168);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (307, 137);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (20, 198);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (868, 226);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (49, 297);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (158, 236);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (885, 158);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (237, 293);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (620, 89);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (667, 201);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (107, 249);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (723, 181);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (760, 91);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (829, 233);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (473, 12);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (812, 101);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (49, 23);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (572, 168);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (856, 194);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (32, 90);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (834, 135);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (835, 237);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (851, 237);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (293, 178);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (433, 188);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (608, 281);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (75, 291);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (844, 92);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (576, 109);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (368, 39);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (387, 123);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (873, 53);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (574, 156);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (680, 254);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (221, 128);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (359, 234);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (268, 256);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (220, 157);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (459, 26);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (786, 252);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (841, 285);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (108, 291);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (959, 165);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (259, 151);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (118, 216);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (650, 153);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (619, 211);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (720, 83);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (802, 51);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (261, 23);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (794, 278);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (105, 282);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (735, 242);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (473, 211);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (621, 140);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (59, 108);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (20, 40);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (45, 260);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (631, 113);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (361, 145);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (849, 147);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (628, 280);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (122, 240);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (678, 131);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (910, 212);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (836, 270);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (103, 22);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (261, 117);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (244, 216);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (338, 289);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (866, 26);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (730, 265);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (610, 298);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (580, 223);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (739, 16);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (974, 151);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (626, 18);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (373, 159);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (927, 275);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (814, 192);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (1, 255);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (813, 272);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (220, 70);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (324, 48);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (571, 54);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (215, 251);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (729, 202);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (77, 264);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (876, 181);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (297, 293);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (780, 114);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (729, 273);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (768, 65);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (79, 275);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (610, 246);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (231, 155);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (804, 148);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (416, 240);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (762, 165);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (758, 234);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (810, 148);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (87, 170);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (290, 111);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (189, 137);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (849, 230);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (132, 85);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (489, 284);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (228, 234);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (523, 168);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (56, 151);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (59, 214);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (696, 263);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (277, 171);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (757, 299);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (889, 15);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (531, 168);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (595, 138);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (827, 154);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (246, 265);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (122, 107);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (881, 137);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (140, 192);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (986, 132);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (37, 19);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (835, 27);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (202, 84);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (475, 176);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (323, 217);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (542, 57);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (835, 240);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (607, 124);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (115, 258);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (645, 112);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (428, 222);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (299, 76);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (435, 222);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (861, 207);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (730, 14);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (400, 199);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (997, 267);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (273, 186);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (603, 214);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (297, 90);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (350, 44);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (415, 284);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (3, 136);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (934, 168);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (181, 175);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (912, 142);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (231, 267);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (700, 120);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (426, 151);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (764, 126);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (662, 254);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (634, 90);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (684, 11);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (868, 178);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (859, 116);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (885, 18);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (361, 293);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (870, 50);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (733, 26);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (733, 183);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (443, 43);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (45, 149);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (935, 120);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (542, 105);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (357, 190);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (566, 100);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (888, 261);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (976, 108);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (410, 70);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (117, 77);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (300, 246);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (536, 214);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (374, 272);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (813, 129);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (849, 231);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (877, 73);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (347, 15);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (315, 267);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (891, 154);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (699, 139);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (765, 158);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (868, 179);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (640, 222);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (187, 56);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (222, 25);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (370, 80);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (532, 266);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (697, 40);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (140, 176);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (844, 219);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (295, 275);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (84, 142);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (310, 231);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (227, 249);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (802, 217);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (354, 62);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (690, 164);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (269, 265);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (574, 198);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (642, 72);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (442, 111);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (213, 28);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (589, 237);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (288, 115);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (218, 93);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (721, 259);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (902, 153);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (852, 290);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (251, 122);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (907, 296);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (725, 28);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (235, 47);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (372, 208);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (457, 9);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (929, 24);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (493, 23);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (356, 89);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (158, 111);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (317, 206);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (613, 95);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (833, 4);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (670, 240);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (623, 74);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (989, 286);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (828, 145);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (485, 222);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (604, 283);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (151, 64);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (554, 181);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (889, 275);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (602, 145);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (205, 41);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (989, 211);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (875, 207);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (989, 18);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (217, 267);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (249, 245);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (538, 72);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (994, 49);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (845, 228);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (967, 144);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (945, 61);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (735, 120);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (685, 282);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (22, 263);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (876, 246);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (537, 141);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (784, 57);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (101, 116);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (966, 202);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (460, 132);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (492, 53);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (466, 7);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (174, 110);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (671, 99);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (622, 182);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (798, 58);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (501, 292);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (302, 112);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (501, 274);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (990, 295);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (962, 252);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (870, 171);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (553, 173);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (491, 237);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (726, 270);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (708, 42);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (604, 36);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (451, 175);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (49, 190);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (734, 251);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (760, 78);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (951, 211);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (299, 178);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (72, 110);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (40, 38);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (947, 37);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (851, 140);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (321, 132);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (909, 152);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (161, 297);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (380, 198);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (59, 152);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (35, 0);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (445, 257);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (331, 268);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (311, 242);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (313, 114);
INSERT INTO bono_credito (cantidad, credito_id) VALUES (330, 124);